<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleblog"
 *
 * Auto generated by Extension Builder 2020-12-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple Blog Extension',
    'description' => 'This is the didactical example from the book \"TYPO3 Extbase\" by Patrick Lobacher',
    'category' => 'plugin',
    'author' => 'Fabio Picciau',
    'author_email' => 'fabio@rncstudio.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
