<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'BK2K\\BootstrapPackage\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes'),
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'PhpParser\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Resources/Private/PHP/PHP-Parser/lib/PhpParser'),
    'Pluswerk\\SimpleBlog\\' => array($typo3InstallDir . 'typo3conf/ext/efempty/Classes'),
    'Pluswerk\\Simpleblog\\' => array($typo3InstallDir . 'typo3conf/ext/simpleblog/Classes'),
);
